# Generated by Django 4.0 on 2022-01-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description',
            field=models.TextField(max_length=2000, null=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='updated_at',
            field=models.DateField(null=True, verbose_name='Дедлайн'),
        ),
    ]
