# Generated by Django 4.0 on 2022-01-03 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_task_description_alter_task_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(default='Подробного описания нет', max_length=2000, null=True, verbose_name='Описание'),
        ),
    ]
